### ISSUE TITLE
demo的链接打不开

### ISSUE THREAD

**Issue by Jasonjiang27** [toddlerya/fakerfactory#1]

**Comment by Jasonjiang27** [comment]
请问有quick start方法吗？

**Comment by toddlerya** [comment]
clone项目到本地后, 进入bin目录下运行二进制文件  
linux可以执行fakerfactory_linux_amd64
macos可以执行fakerfactory_darwin_amd64
服务启动后，可以在浏览器访问
http://127.0.0.1:8001/api/v1/fakerfactory?number=1&columns=color,job,name,sex,address,idcard,age,mobilephone,email,imid,nickname,username,password,website,url,airport,voyage,airlineinfo,traintrips,trainseat,flightseat,ipv4,ipv6,useragent,mac,imsi,imei,meid,deviceid,telphone,citycode,specialphone,capturetime,date

**Comment by Jasonjiang27** [comment]
@toddlerya  感谢大佬回答，另外请问这个二进制文件生成的命令是什么？如果我有一个自定义字段，在代码中添加了可以push上来吗？

**Comment by Jasonjiang27** [comment]
这个二进制文件是 go build 生成的吗？

**Comment by toddlerya** [comment]
> 这个二进制文件是 go build 生成的吗？

是的，go build生成的

**Comment by toddlerya** [comment]
> @toddlerya 感谢大佬回答，另外请问这个二进制文件生成的命令是什么？如果我有一个自定义字段，在代码中添加了可以push上来吗？

你可以fork项目，增加好字段，更新说明文档发起PR。
